spring:
  h2:
    console:
      path: /h2-console/semantic
      # enabled web
      enabled: true
    demo:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    url: jdbc:h2:mem:semantic;DATABASE_TO_UPPER=false
    username: root
    password: semantic

server:
  port: 9080

authentication:
  enable: true
  exclude:
    path: /api/auth/user/register,/api/auth/user/login
  token:
    http:
      header:
        key: Authorization

semantic:
  url:
    prefix: http://127.0.0.1:9081

time:
  threshold: 100

mybatis:
  mapper-locations=classpath:mappers/custom/*.xml,classpath*:/mappers/*.xml

llm:
  url: http://127.0.0.1:9092
embedding:
  url: http://127.0.0.1:9092
functionCall:
  url: http://127.0.0.1:9092
